# Generated by Django 3.1.7 on 2021-02-23 19:48

import ProyectoWebApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('numeroArbol', models.IntegerField(default=-1)),
                ('distanciaEntrePlantas', models.FloatField(blank=True, default=-1, null=True)),
                ('distanciaAlMuro', models.FloatField(blank=True, default=-1, null=True)),
                ('altura', models.FloatField(blank=True, default=-1, null=True)),
                ('circunferenciaDelArbol', models.FloatField()),
                ('cazuela', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Arbol',
                'verbose_name_plural': 'Arboles',
            },
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('numeroFrente', models.IntegerField(blank=True, default=-1, null=True)),
                ('anchoVereda', models.FloatField(blank=True, default=-1, null=True)),
                ('paridad', models.CharField(blank=True, max_length=50, null=True)),
                ('transito', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
            },
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField(default=-1)),
                ('longitud', models.FloatField(default=-1)),
            ],
            options={
                'verbose_name': 'Coordenada',
                'verbose_name_plural': 'Coordenadas',
            },
        ),
        migrations.CreateModel(
            name='EstadoDelArbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoSanitario', models.CharField(blank=True, max_length=50, null=True)),
                ('inclinacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ahuecamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('luminaria', models.CharField(blank=True, max_length=50, null=True)),
                ('danios', models.CharField(blank=True, max_length=50, null=True)),
                ('veredas', models.CharField(blank=True, max_length=50, null=True)),
                ('podas', models.CharField(blank=True, max_length=50, null=True)),
                ('cordon', models.FloatField(blank=True, null=True)),
                ('superficieAfectada', models.IntegerField(blank=True, null=True)),
                ('afecto', models.CharField(blank=True, max_length=50, null=True)),
                ('cables', models.CharField(blank=True, max_length=50, null=True)),
                ('raices', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'EstadoSanitario',
                'verbose_name_plural': 'EstadosSanitarios',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ProyectoWebApp.models.get_image_filename, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Censo',
                'verbose_name_plural': 'Censos',
            },
        ),
    ]
